[package]
name = "dpu-cluster-frontend"
version = "0.1.0"
authors = ["jchauzi <jchauzi@upmem.com>"]

[dependencies]
dpu-cluster-core = { path = "../dpu-cluster-core" }
serde = "1.0.82"
serde_derive = "1.0.82"
serde_json = "1.0.33"